### PR TITLE
Create 2022-12-06-Jumman-Hossain.md

### PR DESCRIPTION
**Pull request by pralgomathic**
initial commit

### CODE REVIEW

**Comment by peterdavidfagan** [comment]
Thanks for opening this pull request @pralgomathic. I am happy to review it and merge the changes once you are finished making changes

**Comment by pralgomathic** [comment]
added some personal information. current access doesn't allow uploading pictures.

**Comment by peterdavidfagan** [comment]
Hi @pralgomathic, 

If you send me the profile image on discord I can look to add a commit for this to the current pull request and have it merged by later today.

**Review by peterdavidfagan — APPROVED** [review]
Followed up on discord regarding the addition of profile image, approving these changes which add a bio.

**Pull request merged**
